server:
  port: 8091

fint:
  adapter:
    endpoints:
      sse: /sse/%s
      status: /status
      response: /response
      providers:
        faktura: https://beta.felleskomponent.no/okonomi/faktura/provider
        kodeverk: https://beta.felleskomponent.no/okonomi/kodeverk/provider

#  oauth:
#    enabled: true
#
#security:
#  basic:
#    enabled: false