server:
  port: 8091

fint:
  adapter:
    endpoints:
      sse: /sse/%s
      status: /status
      response: /response
      providers:
        personal: https://beta.felleskomponent.no/administrasjon/personal/provider
        kodeverk: https://beta.felleskomponent.no/administrasjon/kodeverk/provider
        fullmakt: https://beta.felleskomponent.no/administrasjon/fullmakt/provider
        organisasjon: https://beta.felleskomponent.no/administrasjon/organisasjon/provider
        ## Denne skal flyttes over på ny url
        ##faktura: https://beta1.felleskomponent.no/betaling/provider

#  oauth:
#    enabled: true
#
#security:
#  basic:
#    enabled: false